// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlU1hjIJn4Z_BRTaWzyFahLghadnE7FZs',
    appId: '1:640685068278:web:286bc3181657a9697741d7',
    messagingSenderId: '640685068278',
    projectId: 'hamsa-flutter-task-mgr',
    authDomain: 'hamsa-flutter-task-mgr.firebaseapp.com',
    storageBucket: 'hamsa-flutter-task-mgr.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoh-rhcW1c8773yRXennXieQ2yF9i8pm0',
    appId: '1:640685068278:android:b1ab09e3acd99d267741d7',
    messagingSenderId: '640685068278',
    projectId: 'hamsa-flutter-task-mgr',
    storageBucket: 'hamsa-flutter-task-mgr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnQcO_mfTAP2KCtjNTpwPixM7QPKApG9w',
    appId: '1:640685068278:ios:e20bcea3f36c06157741d7',
    messagingSenderId: '640685068278',
    projectId: 'hamsa-flutter-task-mgr',
    storageBucket: 'hamsa-flutter-task-mgr.firebasestorage.app',
    iosBundleId: 'com.example.hamsaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnQcO_mfTAP2KCtjNTpwPixM7QPKApG9w',
    appId: '1:640685068278:ios:e20bcea3f36c06157741d7',
    messagingSenderId: '640685068278',
    projectId: 'hamsa-flutter-task-mgr',
    storageBucket: 'hamsa-flutter-task-mgr.firebasestorage.app',
    iosBundleId: 'com.example.hamsaFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlU1hjIJn4Z_BRTaWzyFahLghadnE7FZs',
    appId: '1:640685068278:web:5926e48bc21595737741d7',
    messagingSenderId: '640685068278',
    projectId: 'hamsa-flutter-task-mgr',
    authDomain: 'hamsa-flutter-task-mgr.firebaseapp.com',
    storageBucket: 'hamsa-flutter-task-mgr.firebasestorage.app',
  );
}
